// <auto-generated />
using System;
using LowOnLegs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LowOnLegs.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("LowOnLegs.Core.Models.DoubleMatch", b =>
                {
                    b.Property<int>("DoubleMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeftPlayer1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeftPlayer2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftTeamScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LeftTeamWon")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RightPlayer1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RightPlayer2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightTeamScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DoubleMatchId");

                    b.HasIndex("LeftPlayer1Id");

                    b.HasIndex("LeftPlayer2Id");

                    b.HasIndex("RightPlayer1Id");

                    b.HasIndex("RightPlayer2Id");

                    b.ToTable("DoubleMatches");
                });

            modelBuilder.Entity("LowOnLegs.Core.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeftPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RightPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("LeftPlayerId");

                    b.HasIndex("RightPlayerId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LowOnLegs.Core.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("EloDoubles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<int>("EloSingles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/klimko.png",
                            Name = "Piotr",
                            Nickname = "Klimko",
                            Surname = "Klimkowski"
                        },
                        new
                        {
                            PlayerId = 2,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/igor.png",
                            Name = "Igor",
                            Nickname = "Igorakowiec",
                            Surname = "Gresista"
                        },
                        new
                        {
                            PlayerId = 3,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/kuba.png",
                            Name = "Jakub",
                            Nickname = "Kuba",
                            Surname = "Stadniczuk"
                        },
                        new
                        {
                            PlayerId = 4,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/braciak.png",
                            Name = "Dawid",
                            Nickname = "Braciak",
                            Surname = "Posała"
                        },
                        new
                        {
                            PlayerId = 5,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/gliwa.png",
                            Name = "Michał",
                            Nickname = "Gliwa",
                            Surname = "Gliwa"
                        },
                        new
                        {
                            PlayerId = 6,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/fred.png",
                            Name = "Adam",
                            Nickname = "Fred",
                            Surname = "Wybraniec"
                        },
                        new
                        {
                            PlayerId = 7,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/karko.jpg",
                            Name = "Karolina",
                            Nickname = "Serwolina",
                            Surname = "Klimko"
                        },
                        new
                        {
                            PlayerId = 8,
                            EloDoubles = 1000,
                            EloSingles = 1000,
                            ImagePath = "/images/hania.jpg",
                            Name = "Hania",
                            Nickname = "Hanula",
                            Surname = "Stencel"
                        });
                });

            modelBuilder.Entity("LowOnLegs.Core.Models.DoubleMatch", b =>
                {
                    b.HasOne("LowOnLegs.Core.Models.Player", "LeftPlayer1")
                        .WithMany()
                        .HasForeignKey("LeftPlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LowOnLegs.Core.Models.Player", "LeftPlayer2")
                        .WithMany()
                        .HasForeignKey("LeftPlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LowOnLegs.Core.Models.Player", "RightPlayer1")
                        .WithMany()
                        .HasForeignKey("RightPlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LowOnLegs.Core.Models.Player", "RightPlayer2")
                        .WithMany()
                        .HasForeignKey("RightPlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LeftPlayer1");

                    b.Navigation("LeftPlayer2");

                    b.Navigation("RightPlayer1");

                    b.Navigation("RightPlayer2");
                });

            modelBuilder.Entity("LowOnLegs.Core.Models.Match", b =>
                {
                    b.HasOne("LowOnLegs.Core.Models.Player", "LeftPlayer")
                        .WithMany("Matches")
                        .HasForeignKey("LeftPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LowOnLegs.Core.Models.Player", "RightPlayer")
                        .WithMany()
                        .HasForeignKey("RightPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LowOnLegs.Core.Models.Player", "Winner")
                        .WithMany("MatchesWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LeftPlayer");

                    b.Navigation("RightPlayer");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("LowOnLegs.Core.Models.Player", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("MatchesWon");
                });
#pragma warning restore 612, 618
        }
    }
}
